import type { SolutionPage } from '../types';

/**
 * Telcobright Billing Solutions
 *
 * Migrated verbatim from https://telcobright.com/telcobright-billing-solutions/
 * Blocks appear in the same order, with the same words, as the old page.
 */
export const page: SolutionPage = {
  slug: "billing-solutions",
  title: "Telcobright Billing Solutions",
  summary: "Telcobright SMS Platform is a highly scalable distributed carrier-grade SMS platform with no single point of failure.",
  legacyPath: "/telcobright-billing-solutions/",
  featured: true,
  blocks: [
    { t: 'h', level: 2, id: "overview", text: "Overview", html: "Overview" },
    { t: 'p', html: "Telcobright" },
    { t: 'p', html: "Billing Solution" },
    { t: 'p', html: "Reporting Solution" },
    { t: 'p', html: "Automation" },
    {
      t: 'ul',
      items: [
        "Telcobright is a Billing &amp; Mediation Software for Telecom Operators, both Retail and Wholesale.",
        "It is also a Stand Alone Reporting Platform, well focused on Performance Monitoring for a transit (interconnect) operators",
        "Batch Processing System for Automation to accomplish complex tasks with minimum human resources",
        "Successful implementation in both models so far",
        "Supports both Text and Binary CDR format",
        "Proven Implementation with leading vendors’ Switch",
        "Support for New CDR Format can be added easily due to Extensible Framework.",
      ],
    },
    { t: 'img', src: "/media/2023/03/Image_010.jpg", alt: "", row: "carousel" },
    { t: 'img', src: "/media/2023/03/cataleya.png", alt: "", row: "carousel" },
    { t: 'img', src: "/media/2023/03/Image_009-1.jpg", alt: "", row: "carousel" },
    { t: 'img', src: "/media/2023/03/zte.png", alt: "", row: "carousel" },
    { t: 'img', src: "/media/2023/03/Image_007.png", alt: "", row: "carousel" },
    { t: 'img', src: "/media/2023/03/Image_006.png", alt: "", row: "carousel" },
    { t: 'h', level: 2, id: "telcobright-capabilities-at-a-glance", text: "Telcobright Capabilities at a glance", html: "Telcobright Capabilities at a glance" },
    { t: 'p', html: "<b>Interconnect Billing</b>" },
    {
      t: 'ul',
      items: [
        "PSTN &amp; VoIP carrier management &amp; billing for transit or wholesale operators",
        "Prepaid/Postpaid Billing",
        "Telecom Post-Paid Subscriber Billing (Mobile, PSTN, Calling Card etc.)",
      ],
    },
    { t: 'p', html: "<b>Advanced Rating &amp; Rate Management</b>" },
    {
      t: 'ul',
      items: [
        "A-Z Destination/Prefix based Rating",
        "Import/Export Rate Sheet from various format, intelligent import utility that can identity &amp; import rates automatically from any format",
        "Ingress/Egress Rating",
        "Peak/Off Peak, Time Based Rating",
      ],
    },
    { t: 'p', html: "<b>Invoice Generation</b>" },
    { t: 'p', html: "<b>Automation</b>" },
    {
      t: 'ul',
      items: [
        "Least Cost Routing, Sending Commands to Network Elements for pre-paid control, Data archiving, backup, maintenance",
      ],
    },
    { t: 'p', html: "<b>Reporting</b>" },
    {
      t: 'ul',
      items: [
        "Very Enhanced, flexible &amp; customizable Reporting for telecom operators",
        "Advanced, Smart Summary for lightning fast reports",
      ],
    },
    { t: 'p', html: "<b>Unified Billing (being developed)</b>" },
    {
      t: 'ul',
      items: [
        "Billing for ISP, IPTV operator",
        "Radius Integration",
      ],
    },
    { t: 'p', html: "<b>Accounting/ERP integration</b>" },
    {
      t: 'ul',
      items: [
        "Integration with SoftSwitch with help of Apache’s top level ERP project Ofbiz for accounting and ERP",
        "Accurate &amp; Reliable Accounting for Voice &amp; Data Business",
      ],
    },
    { t: 'p', html: "<b>Technical Excellence</b>" },
    {
      t: 'ul',
      items: [
        "Very Reliable &amp; Accurate",
        "Lightning Fast",
        "Efficient Compression in Database, takes 1/6 th space comparing to competitor’s solution",
      ],
    },
    { t: 'img', src: "/media/2023/03/4.webp", alt: "" },
    { t: 'h', level: 2, id: "rating-billing-features", text: "Rating & Billing Features", html: "Rating &amp; Billing Features" },
    { t: 'img', src: "/media/2023/03/5.webp", alt: "" },
    { t: 'h', level: 2, id: "handling-various-services-with-telcobright", text: "Handling Various Services with telcobright", html: "Handling Various Services with telcobright" },
    { t: 'img', src: "/media/2023/03/6.webp", alt: "" },
    { t: 'h', level: 2, id: "rate-plan-assignment-with-effective-date", text: "Rate plan Assignment with effective Date", html: "Rate plan Assignment with effective Date" },
    { t: 'img', src: "/media/2023/03/7.webp", alt: "" },
    { t: 'h', level: 2, id: "individual-rate-assignment-with-effective-date", text: "Individual rate assignment with effective date", html: "Individual rate assignment with effective date" },
    { t: 'img', src: "/media/2023/03/8.webp", alt: "" },
    { t: 'h', level: 2, id: "rate-sheet-import-wizard", text: "Rate sheet import wizard", html: "Rate sheet import wizard" },
    { t: 'img', src: "/media/2023/03/9.webp", alt: "" },
    { t: 'h', level: 2, id: "dynamic-least-cost-routin-lcr", text: "Dynamic least cost routin(LCR)", html: "Dynamic least cost routin(LCR)" },
    { t: 'img', src: "/media/2023/03/10.webp", alt: "" },
    { t: 'img', src: "/media/2023/03/11.webp", alt: "" },
    { t: 'h', level: 2, id: "modules", text: "Modules", html: "Modules" },
    { t: 'img', src: "/media/2023/03/12.webp", alt: "" },
    { t: 'h', level: 2, id: "platform-operating-system", text: "Platform & Operating System", html: "Platform &amp; Operating System" },
    { t: 'img', src: "/media/2023/03/13.webp", alt: "" },
    { t: 'h', level: 2, id: "database-compression-true-multi-master-architecture", text: "Database-compression & True Multi Master Architecture", html: "Database-compression &amp; True Multi Master Architecture" },
    { t: 'img', src: "/media/2023/03/14.webp", alt: "" },
    { t: 'h', level: 2, id: "hardware-requirement-1", text: "Hardware Requirement-1", html: "Hardware Requirement-1" },
    { t: 'img', src: "/media/2023/03/15.webp", alt: "" },
    { t: 'h', level: 2, id: "hardware-requirement-2", text: "Hardware Requirement-2", html: "Hardware Requirement-2" },
    { t: 'img', src: "/media/2023/03/16.webp", alt: "" },
    { t: 'h', level: 2, id: "checklist-to-compare-telcobright-with-competitions-1", text: "Checklist to compare telcobright with competitions-1", html: "Checklist to compare telcobright with competitions-1" },
    { t: 'img', src: "/media/2023/03/17.webp", alt: "" },
    { t: 'h', level: 2, id: "checklist-to-compare-telcobright-with-competitions-2", text: "Checklist to compare telcobright with competitions-2", html: "Checklist to compare telcobright with competitions-2" },
    { t: 'img', src: "/media/2023/03/18.webp", alt: "" },
    { t: 'h', level: 2, id: "smart-summary", text: "Smart Summary", html: "Smart Summary" },
    { t: 'img', src: "/media/2023/03/19.webp", alt: "" },
    { t: 'h', level: 2, id: "smart-summary-one-version-of-data", text: "Smart Summary(One version of data)", html: "Smart Summary(One version of data)" },
    { t: 'img', src: "/media/2023/03/20.webp", alt: "" },
    { t: 'h', level: 2, id: "smart-summary-real-time", text: "Smart Summary(Real Time)", html: "Smart Summary(Real Time)" },
    { t: 'img', src: "/media/2023/03/21.webp", alt: "" },
    { t: 'h', level: 2, id: "smart-summary-detailed-deep", text: "Smart Summary(Detailed & Deep)", html: "Smart Summary(Detailed &amp; Deep)" },
    { t: 'img', src: "/media/2023/03/22.webp", alt: "" },
    { t: 'h', level: 2, id: "partial-cdr-handling-1", text: "Partial CDR Handling-1", html: "Partial CDR Handling-1" },
    { t: 'img', src: "/media/2023/03/23.webp", alt: "" },
    { t: 'h', level: 2, id: "partial-cdr-handling-2", text: "Partial CDR Handling-2", html: "Partial CDR Handling-2" },
    { t: 'img', src: "/media/2023/03/24.webp", alt: "" },
    { t: 'h', level: 2, id: "minimum-administrative-effort", text: "Minimum Administrative Effort", html: "Minimum Administrative Effort" },
    { t: 'img', src: "/media/2023/03/25.webp", alt: "" },
    { t: 'h', level: 2, id: "navigation-section-of-the-web-gui", text: "Navigation section of the web GUI", html: "Navigation section of the web GUI" },
    { t: 'img', src: "/media/2023/03/26.webp", alt: "" },
    { t: 'img', src: "/media/2023/03/27.webp", alt: "" },
    { t: 'h', level: 2, id: "a-reporting-screen-with-important-options", text: "A reporting screen with important options", html: "A reporting screen with important options" },
    { t: 'img', src: "/media/2023/03/28.webp", alt: "" },
    { t: 'h', level: 2, id: "short-desciption-of-important-reporting-options", text: "Short desciption of important reporting options", html: "Short desciption of important reporting options" },
    { t: 'img', src: "/media/2023/03/29.webp", alt: "" },
    { t: 'h', level: 2, id: "a-very-basic-report", text: "A very basic report", html: "A very basic report" },
    { t: 'img', src: "/media/2023/03/30.webp", alt: "" },
    { t: 'h', level: 2, id: "a-report-with-few-selection-parameters", text: "A report with few selection parameters", html: "A report with few selection parameters" },
    { t: 'img', src: "/media/2023/03/31.webp", alt: "" },
    { t: 'h', level: 2, id: "a-report-which-can-answer-a-more-complex-question", text: "A report which can answer a more complex question", html: "A report which can answer a more complex question" },
    { t: 'img', src: "/media/2023/03/32.webp", alt: "" },
    { t: 'h', level: 2, id: "a-report-on-cause-code-status", text: "A report on cause code status", html: "A report on cause code status" },
    { t: 'img', src: "/media/2023/03/33.webp", alt: "" },
    { t: 'h', level: 2, id: "viewing-the-actual-calls-in-a-cause-code-group", text: "Viewing the actual calls in a cause code group", html: "Viewing the actual calls in a cause code group" },
    { t: 'img', src: "/media/2023/03/34.webp", alt: "" },
    { t: 'h', level: 2, id: "route-utilization-report-ingress-egress", text: "Route utilization report (Ingress & Egress)", html: "Route utilization report (Ingress &amp; Egress)" },
    { t: 'img', src: "/media/2023/03/35.webp", alt: "" },
    { t: 'h', level: 2, id: "route-utilization-report-aggregate", text: "Route Utilization Report (Aggregate)", html: "Route Utilization Report (Aggregate)" },
    { t: 'img', src: "/media/2023/03/36.webp", alt: "" },
    { t: 'h', level: 2, id: "mediation-reports-tasks", text: "Mediation Reports & Tasks", html: "Mediation Reports &amp; Tasks" },
    { t: 'img', src: "/media/2023/03/37.webp", alt: "" },
    { t: 'img', src: "/media/2023/03/38.webp", alt: "" },
    { t: 'h', level: 2, id: "file-inventory-cdr-files-processing-status", text: "File Inventory: CDR Files Processing Status", html: "File Inventory: CDR Files Processing Status" },
    { t: 'img', src: "/media/2023/03/39.webp", alt: "" },
    { t: 'h', level: 2, id: "file-sending-to-iof-btrc-or-archive-backup", text: "File sending to IOF/BTRC or Archive (Backup)", html: "File sending to IOF/BTRC or Archive (Backup)" },
    { t: 'img', src: "/media/2023/03/40.webp", alt: "" },
    { t: 'h', level: 2, id: "always-monitor-important-things-from-dashboard", text: "Always monitor important things from Dashboard", html: "Always monitor important things from Dashboard" },
    { t: 'img', src: "/media/2023/03/41.webp", alt: "" },
    { t: 'h', level: 2, id: "accounting-features-leverage-the-power-of-erp-apache-top-lev", text: "Accounting features, leverage the power of ERP(Apache top level project \"Ofbiz\")", html: "Accounting features, leverage the power of ERP(Apache top level project \"Ofbiz\")" },
    { t: 'img', src: "/media/2023/03/42.webp", alt: "" },
    { t: 'h', level: 2, id: "invoice-in-accounts-receivable", text: "Invoice in accounts receivable", html: "Invoice in accounts receivable" },
    { t: 'img', src: "/media/2023/03/43.webp", alt: "" },
    { t: 'h', level: 2, id: "invoice-bills-in-accounts-payable", text: "Invoice (Bills) in accounts payable", html: "Invoice (Bills) in accounts payable" },
    { t: 'img', src: "/media/2023/03/44.webp", alt: "" },
    { t: 'h', level: 2, id: "managing-invoices-e-g-approving-sending-etc", text: "Managing Invoices e.g approving, sending etc.", html: "Managing Invoices e.g approving, sending etc." },
    { t: 'img', src: "/media/2023/03/45-1.webp", alt: "" },
    { t: 'h', level: 2, id: "receiving-a-payment-and-appling-to-invoice", text: "Receiving a payment and appling to invoice", html: "Receiving a payment and appling to invoice" },
    { t: 'img', src: "/media/2023/03/46-1.webp", alt: "" },
    { t: 'h', level: 2, id: "integrate-accounts-payment-directly-with-switching-system", text: "Integrate accounts(Payment) Directly with switching system", html: "Integrate accounts(Payment) Directly with switching system" },
    { t: 'img', src: "/media/2023/03/47.webp", alt: "" },
    { t: 'h', level: 2, id: "useful-features-for-igx-icx", text: "Useful features for IGX & ICX", html: "Useful features for IGX &amp; ICX" },
    { t: 'img', src: "/media/2023/03/48.webp", alt: "" },
  ],
};
